-- Creation of Database
DROP DATABASE IF EXISTS fifaDatabase;
CREATE DATABASE fifaDatabase DEFAULT CHARACTER SET utf8;
USE fifaDatabase;

-- Creation of fifa22 table
DROP TABLE IF EXISTS fifaData;
CREATE TABLE IF NOT EXISTS fifaData(
	gender VARCHAR(2),
    fifaYear VARCHAR(10),
	sofifa_id MEDIUMINT NOT NULL,
    player_url VARCHAR(100),
    short_name VARCHAR(50) NOT NULL,
    long_name VARCHAR(50) NOT NULL,
    player_positions VARCHAR(50) NOT NULL,
    overall SMALLINT NOT NULL,
    potential SMALLINT NOT NULL,
    value_eur BIGINT,
    wage_eur BIGINT,
    age SMALLINT NOT NULL,
    dob VARCHAR(15),
    height_cm SMALLINT NOT NULL,
    weight_kg SMALLINT NOT NULL,
    club_team_id INT,
    club_name VARCHAR(100),
    league_name VARCHAR(100),
    league_level VARCHAR(100),
    club_position VARCHAR(10),
    club_jersey_number SMALLINT,
    club_loaned_from VARCHAR(100),
    club_joined VARCHAR(100),
    club_contract_valid_until YEAR,
    nationality_id INT,
    nationality_name VARCHAR(100),
    nation_team_id INT,
    nation_position VARCHAR(10),
    nation_jersey_number SMALLINT,
    preferred_foot VARCHAR(10),
    weak_foot SMALLINT,
    skill_moves SMALLINT,
    international_reputation SMALLINT,
    work_rate VARCHAR(50),
    body_type VARCHAR(30),
    real_face VARCHAR(10),
    release_clause_eur BIGINT,
    player_tags VARCHAR(200),
    player_traits VARCHAR(200),
    pace MEDIUMINT,
    shooting MEDIUMINT,
    passing MEDIUMINT,
    dribbling MEDIUMINT,
    defending MEDIUMINT,
    physic MEDIUMINT,
    attacking_crossing MEDIUMINT,
    attacking_finishing MEDIUMINT,
    attacking_heading_accuracy MEDIUMINT,
    attacking_short_passing MEDIUMINT,
    attacking_volleys MEDIUMINT,
    skill_dribbling MEDIUMINT,
    skill_curve MEDIUMINT,
    skill_fk_accuracy MEDIUMINT,
    skill_long_passing MEDIUMINT,
    skill_ball_control MEDIUMINT,
    movement_acceleration MEDIUMINT,
    movement_sprint_speed MEDIUMINT,
    movement_agility MEDIUMINT,
    movement_reactions MEDIUMINT,
    movement_balance MEDIUMINT,
    power_shot_power MEDIUMINT,
    power_jumping MEDIUMINT,
    power_stamina MEDIUMINT,
    power_strength MEDIUMINT,
    power_long_shots MEDIUMINT,
    mentality_aggression MEDIUMINT,
    mentality_interceptions MEDIUMINT,
    mentality_positioning MEDIUMINT,
    mentality_vision MEDIUMINT,
    mentality_penalties MEDIUMINT,
    mentality_composure MEDIUMINT,
    defending_marking_awareness MEDIUMINT,
    defending_standing_tackle MEDIUMINT,
    defending_sliding_tackle MEDIUMINT,
    goalkeeping_diving MEDIUMINT,
    goalkeeping_handling MEDIUMINT,
    goalkeeping_kicking MEDIUMINT,
    goalkeeping_positioning MEDIUMINT,
    goalkeeping_reflexes MEDIUMINT,
    goalkeeping_speed MEDIUMINT,
    ls VARCHAR(15),
    st VARCHAR(15),
    rs VARCHAR(15),
    lw VARCHAR(15),
    lf VARCHAR(15),
    cf VARCHAR(15),
    rf VARCHAR(15),
    rw VARCHAR(15),
    lam VARCHAR(15),
    cam VARCHAR(15),
    ram VARCHAR(15),
    lm VARCHAR(15),
    lcm VARCHAR(15),
    cm VARCHAR(15),
    rcm VARCHAR(15),
    rm VARCHAR(15),
    lwb VARCHAR(15),
    ldm VARCHAR(15),
    cdm VARCHAR(15),
    rdm VARCHAR(15),
    rwb VARCHAR(15),
    lb VARCHAR(15),
    lcb VARCHAR(15),
    cb VARCHAR(15),
    rcb VARCHAR(15),
    rb VARCHAR(15),
    gk VARCHAR(15),
    player_face_url VARCHAR(150),
    club_logo_url VARCHAR(150),
    club_flag_url VARCHAR(150),
    nation_logo_url VARCHAR(150),
    nation_flag_url VARCHAR(150)
);

-- Loading data from CSV file into mega table
LOAD DATA INFILE 'c:\\wamp64\\tmp\\fifaProj\\players_22.csv' INTO TABLE fifaData 
	FIELDS ENCLOSED BY '"' TERMINATED BY ','
	LINES TERMINATED BY '\n'
    IGNORE 1 ROWS
    
    (gender, fifaYear, sofifa_id, player_url, short_name, long_name, player_positions, overall, potential,@value_eur, @wage_eur, age, dob, height_cm, 
    weight_kg, @club_team_id, club_name, league_name, league_level, club_position, @club_jersey_number, club_loaned_from, club_joined, 
    @club_contract_valid_until, nationality_id, nationality_name, @nation_team_id, nation_position, @nation_jersey_number, preferred_foot,
    weak_foot, skill_moves, international_reputation, work_rate, body_type, real_face, @release_clause_eur, player_tags, player_traits,
    @pace, @shooting, @passing, @dribbling, @defending, @physic, @attacking_crossing, @attacking_finishing, @attacking_heading_accuracy, 
    @attacking_short_passing, @attacking_volleys, @skill_dribbling, @skill_curve, @skill_fk_accuracy, @skill_long_passing, @skill_ball_control, 
    @movement_acceleration, @movement_sprint_speed, @movement_agility, @movement_reactions, @movement_balance, @power_shot_power, @power_jumping, 
    @power_stamina, @power_strength, @power_long_shots, @mentality_aggression, @mentality_interceptions, @mentality_positioning, @mentality_vision, 
    @mentality_penalties, @mentality_composure, @defending_marking_awareness, @defending_standing_tackle, @defending_sliding_tackle, @goalkeeping_diving, 
    @goalkeeping_handling, @goalkeeping_kicking, @goalkeeping_positioning, @goalkeeping_reflexes, @goalkeeping_speed, ls, st, rs, lw, lf, cf, rf, rw, lam, cam, ram, 
    lm, lcm, cm, rcm, rm, lwb, ldm, cdm, rdm, rwb, lb, lcb, cb, rcb, rb, gk, player_face_url,club_logo_url,club_flag_url,
    nation_logo_url, nation_flag_url)
    SET
		value_eur = NULLIF(@value_eur, ''),
        wage_eur = NULLIF(@wage_eur, ''),
        club_team_id = NULLIF(@club_team_id, ''),
        club_jersey_number = NULLIF(@club_jersey_number, ''),
        club_contract_valid_until = NULLIF(@club_contract_valid_until, ''),
		nation_team_id = NULLIF(@nation_team_id, ''),
        nation_jersey_number = NULLIF(@nation_jersey_number, ''),
        release_clause_eur = NULLIF(@release_clause_eur, ''),
        pace = NULLIF(@pace, ''), 
        shooting = NULLIF(@shooting, ''), 
        passing = NULLIF(@passing, ''), 
        dribbling = NULLIF(@dribbling, ''), 
        defending = NULLIF(@defending, ''), 
        physic = NULLIF(@physic, ''), 
        attacking_crossing = NULLIF(@attacking_crossing, ''), 
        attacking_finishing = NULLIF(@attacking_finishing, ''), 
        attacking_heading_accuracy = NULLIF(@attacking_heading_accuracy, ''), 
		attacking_short_passing = NULLIF(@attacking_short_passing, ''), 
        attacking_volleys = NULLIF(@attacking_volleys, ''), 
        skill_dribbling = NULLIF(@skill_dribbling, ''), 
        skill_curve = NULLIF(@skill_curve, ''), 
        skill_fk_accuracy = NULLIF(@skill_fk_accuracy, ''), 
        skill_long_passing = NULLIF(@skill_long_passing, ''), 
        skill_ball_control = NULLIF(@skill_ball_control, ''), 
		movement_acceleration = NULLIF(@movement_acceleration, ''), 
        movement_sprint_speed = NULLIF(@movement_sprint_speed, ''), 
        movement_agility = NULLIF(@movement_agility, ''), 
        movement_reactions = NULLIF(@movement_reactions, ''), 
        movement_balance = NULLIF(@movement_balance, ''), 
        power_shot_power = NULLIF(@power_shot_power, ''), 
        power_jumping = NULLIF(@power_jumping, ''), 
		power_stamina = NULLIF(@power_stamina, ''), 
        power_strength = NULLIF(@power_strength, ''), 
        power_long_shots = NULLIF(@power_long_shots, ''), 
        mentality_aggression = NULLIF(@mentality_aggression, ''), 
        mentality_interceptions = NULLIF(@mentality_interceptions, ''), 
        mentality_positioning = NULLIF(@mentality_positioning,''), 
        mentality_vision = NULLIF(@mentality_vision, ''), 
		mentality_penalties = NULLIF(@mentality_penalties, ''), 
        mentality_composure = NULLIF(@mentality_composure, ''), 
        defending_marking_awareness = NULLIF(@defending_marking_awareness, ''), 
        defending_standing_tackle = NULLIF(@defending_standing_tackle, ''), 
        defending_sliding_tackle = NULLIF(@defending_sliding_tackle, ''), 
        goalkeeping_diving = NULLIF(@goalkeeping_diving, ''), 
		goalkeeping_handling = NULLIF(@goalkeeping_handling, ''), 
        goalkeeping_kicking = NULLIF(@goalkeeping_kicking, ''), 
        goalkeeping_positioning = NULLIF(@goalkeeping_positioning, ''), 
        goalkeeping_reflexes = NULLIF(@goalkeeping_reflexes, ''), 
        goalkeeping_speed = NULLIF(@goalkeeping_speed, '');

        


-- Loading data from CSV file into mega table
LOAD DATA INFILE 'c:\\wamp64\\tmp\\fifaProj\\female_players_22.csv' INTO TABLE fifaData 
	FIELDS ENCLOSED BY '"' TERMINATED BY ','
	LINES TERMINATED BY '\n'
    IGNORE 1 ROWS
    
    (gender, fifaYear, sofifa_id, player_url, short_name, long_name, player_positions, overall, potential,@value_eur, @wage_eur, age, dob, height_cm, 
    weight_kg, @club_team_id, club_name, league_name, league_level, club_position, @club_jersey_number, club_loaned_from, club_joined, 
    @club_contract_valid_until, nationality_id, nationality_name, @nation_team_id, nation_position, @nation_jersey_number, preferred_foot,
    weak_foot, skill_moves, international_reputation, work_rate, body_type, real_face, @release_clause_eur, player_tags, player_traits,
    @pace, @shooting, @passing, @dribbling, @defending, @physic, @attacking_crossing, @attacking_finishing, @attacking_heading_accuracy, 
    @attacking_short_passing, @attacking_volleys, @skill_dribbling, @skill_curve, @skill_fk_accuracy, @skill_long_passing, @skill_ball_control, 
    @movement_acceleration, @movement_sprint_speed, @movement_agility, @movement_reactions, @movement_balance, @power_shot_power, @power_jumping, 
    @power_stamina, @power_strength, @power_long_shots, @mentality_aggression, @mentality_interceptions, @mentality_positioning, @mentality_vision, 
    @mentality_penalties, @mentality_composure, @defending_marking_awareness, @defending_standing_tackle, @defending_sliding_tackle, @goalkeeping_diving, 
    @goalkeeping_handling, @goalkeeping_kicking, @goalkeeping_positioning, @goalkeeping_reflexes, @goalkeeping_speed, ls, st, rs, lw, lf, cf, rf, rw, lam, cam, ram, 
    lm, lcm, cm, rcm, rm, lwb, ldm, cdm, rdm, rwb, lb, lcb, cb, rcb, rb, gk, player_face_url,club_logo_url,club_flag_url,
    nation_logo_url, nation_flag_url)
    SET
		value_eur = NULLIF(@value_eur, ''),
        wage_eur = NULLIF(@wage_eur, ''),
        club_team_id = NULLIF(@club_team_id, ''),
        club_jersey_number = NULLIF(@club_jersey_number, ''),
        club_contract_valid_until = NULLIF(@club_contract_valid_until, ''),
		nation_team_id = NULLIF(@nation_team_id, ''),
        nation_jersey_number = NULLIF(@nation_jersey_number, ''),
        release_clause_eur = NULLIF(@release_clause_eur, ''),
        pace = NULLIF(@pace, ''), 
        shooting = NULLIF(@shooting, ''), 
        passing = NULLIF(@passing, ''), 
        dribbling = NULLIF(@dribbling, ''), 
        defending = NULLIF(@defending, ''), 
        physic = NULLIF(@physic, ''), 
        attacking_crossing = NULLIF(@attacking_crossing, ''), 
        attacking_finishing = NULLIF(@attacking_finishing, ''), 
        attacking_heading_accuracy = NULLIF(@attacking_heading_accuracy, ''), 
		attacking_short_passing = NULLIF(@attacking_short_passing, ''), 
        attacking_volleys = NULLIF(@attacking_volleys, ''), 
        skill_dribbling = NULLIF(@skill_dribbling, ''), 
        skill_curve = NULLIF(@skill_curve, ''), 
        skill_fk_accuracy = NULLIF(@skill_fk_accuracy, ''), 
        skill_long_passing = NULLIF(@skill_long_passing, ''), 
        skill_ball_control = NULLIF(@skill_ball_control, ''), 
		movement_acceleration = NULLIF(@movement_acceleration, ''), 
        movement_sprint_speed = NULLIF(@movement_sprint_speed, ''), 
        movement_agility = NULLIF(@movement_agility, ''), 
        movement_reactions = NULLIF(@movement_reactions, ''), 
        movement_balance = NULLIF(@movement_balance, ''), 
        power_shot_power = NULLIF(@power_shot_power, ''), 
        power_jumping = NULLIF(@power_jumping, ''), 
		power_stamina = NULLIF(@power_stamina, ''), 
        power_strength = NULLIF(@power_strength, ''), 
        power_long_shots = NULLIF(@power_long_shots, ''), 
        mentality_aggression = NULLIF(@mentality_aggression, ''), 
        mentality_interceptions = NULLIF(@mentality_interceptions, ''), 
        mentality_positioning = NULLIF(@mentality_positioning,''), 
        mentality_vision = NULLIF(@mentality_vision, ''), 
		mentality_penalties = NULLIF(@mentality_penalties, ''), 
        mentality_composure = NULLIF(@mentality_composure, ''), 
        defending_marking_awareness = NULLIF(@defending_marking_awareness, ''), 
        defending_standing_tackle = NULLIF(@defending_standing_tackle, ''), 
        defending_sliding_tackle = NULLIF(@defending_sliding_tackle, ''), 
        goalkeeping_diving = NULLIF(@goalkeeping_diving, ''), 
		goalkeeping_handling = NULLIF(@goalkeeping_handling, ''), 
        goalkeeping_kicking = NULLIF(@goalkeeping_kicking, ''), 
        goalkeeping_positioning = NULLIF(@goalkeeping_positioning, ''), 
        goalkeeping_reflexes = NULLIF(@goalkeeping_reflexes, ''), 
        goalkeeping_speed = NULLIF(@goalkeeping_speed, '');



-- Loading data from CSV file into mega table
LOAD DATA INFILE 'c:\\wamp64\\tmp\\fifaProj\\players_21.csv' INTO TABLE fifaData 
	FIELDS ENCLOSED BY '"' TERMINATED BY ','
	LINES TERMINATED BY '\n'
    IGNORE 1 ROWS
    
    (gender, fifaYear, sofifa_id, player_url, short_name, long_name, player_positions, overall, potential,@value_eur, @wage_eur, age, dob, height_cm, 
    weight_kg, @club_team_id, club_name, league_name, league_level, club_position, @club_jersey_number, club_loaned_from, club_joined, 
    @club_contract_valid_until, nationality_id, nationality_name, @nation_team_id, nation_position, @nation_jersey_number, preferred_foot,
    weak_foot, skill_moves, international_reputation, work_rate, body_type, real_face, @release_clause_eur, player_tags, player_traits,
    @pace, @shooting, @passing, @dribbling, @defending, @physic, @attacking_crossing, @attacking_finishing, @attacking_heading_accuracy, 
    @attacking_short_passing, @attacking_volleys, @skill_dribbling, @skill_curve, @skill_fk_accuracy, @skill_long_passing, @skill_ball_control, 
    @movement_acceleration, @movement_sprint_speed, @movement_agility, @movement_reactions, @movement_balance, @power_shot_power, @power_jumping, 
    @power_stamina, @power_strength, @power_long_shots, @mentality_aggression, @mentality_interceptions, @mentality_positioning, @mentality_vision, 
    @mentality_penalties, @mentality_composure, @defending_marking_awareness, @defending_standing_tackle, @defending_sliding_tackle, @goalkeeping_diving, 
    @goalkeeping_handling, @goalkeeping_kicking, @goalkeeping_positioning, @goalkeeping_reflexes, @goalkeeping_speed, ls, st, rs, lw, lf, cf, rf, rw, lam, cam, ram, 
    lm, lcm, cm, rcm, rm, lwb, ldm, cdm, rdm, rwb, lb, lcb, cb, rcb, rb, gk, player_face_url,club_logo_url,club_flag_url,
    nation_logo_url, nation_flag_url)
    SET
		value_eur = NULLIF(@value_eur, ''),
        wage_eur = NULLIF(@wage_eur, ''),
        club_team_id = NULLIF(@club_team_id, ''),
        club_jersey_number = NULLIF(@club_jersey_number, ''),
        club_contract_valid_until = NULLIF(@club_contract_valid_until, ''),
		nation_team_id = NULLIF(@nation_team_id, ''),
        nation_jersey_number = NULLIF(@nation_jersey_number, ''),
        release_clause_eur = NULLIF(@release_clause_eur, ''),
        pace = NULLIF(@pace, ''), 
        shooting = NULLIF(@shooting, ''), 
        passing = NULLIF(@passing, ''), 
        dribbling = NULLIF(@dribbling, ''), 
        defending = NULLIF(@defending, ''), 
        physic = NULLIF(@physic, ''), 
        attacking_crossing = NULLIF(@attacking_crossing, ''), 
        attacking_finishing = NULLIF(@attacking_finishing, ''), 
        attacking_heading_accuracy = NULLIF(@attacking_heading_accuracy, ''), 
		attacking_short_passing = NULLIF(@attacking_short_passing, ''), 
        attacking_volleys = NULLIF(@attacking_volleys, ''), 
        skill_dribbling = NULLIF(@skill_dribbling, ''), 
        skill_curve = NULLIF(@skill_curve, ''), 
        skill_fk_accuracy = NULLIF(@skill_fk_accuracy, ''), 
        skill_long_passing = NULLIF(@skill_long_passing, ''), 
        skill_ball_control = NULLIF(@skill_ball_control, ''), 
		movement_acceleration = NULLIF(@movement_acceleration, ''), 
        movement_sprint_speed = NULLIF(@movement_sprint_speed, ''), 
        movement_agility = NULLIF(@movement_agility, ''), 
        movement_reactions = NULLIF(@movement_reactions, ''), 
        movement_balance = NULLIF(@movement_balance, ''), 
        power_shot_power = NULLIF(@power_shot_power, ''), 
        power_jumping = NULLIF(@power_jumping, ''), 
		power_stamina = NULLIF(@power_stamina, ''), 
        power_strength = NULLIF(@power_strength, ''), 
        power_long_shots = NULLIF(@power_long_shots, ''), 
        mentality_aggression = NULLIF(@mentality_aggression, ''), 
        mentality_interceptions = NULLIF(@mentality_interceptions, ''), 
        mentality_positioning = NULLIF(@mentality_positioning,''), 
        mentality_vision = NULLIF(@mentality_vision, ''), 
		mentality_penalties = NULLIF(@mentality_penalties, ''), 
        mentality_composure = NULLIF(@mentality_composure, ''), 
        defending_marking_awareness = NULLIF(@defending_marking_awareness, ''), 
        defending_standing_tackle = NULLIF(@defending_standing_tackle, ''), 
        defending_sliding_tackle = NULLIF(@defending_sliding_tackle, ''), 
        goalkeeping_diving = NULLIF(@goalkeeping_diving, ''), 
		goalkeeping_handling = NULLIF(@goalkeeping_handling, ''), 
        goalkeeping_kicking = NULLIF(@goalkeeping_kicking, ''), 
        goalkeeping_positioning = NULLIF(@goalkeeping_positioning, ''), 
        goalkeeping_reflexes = NULLIF(@goalkeeping_reflexes, ''), 
        goalkeeping_speed = NULLIF(@goalkeeping_speed, '');
        
        
        
        
        



-- Loading data from CSV file into mega table
LOAD DATA INFILE 'c:\\wamp64\\tmp\\fifaProj\\female_players_21.csv' INTO TABLE fifaData
	FIELDS ENCLOSED BY '"' TERMINATED BY ','
	LINES TERMINATED BY '\n'
    IGNORE 1 ROWS
    
    (gender, fifaYear, sofifa_id, player_url, short_name, long_name, player_positions, overall, potential,@value_eur, @wage_eur, age, dob, height_cm, 
    weight_kg, @club_team_id, club_name, league_name, league_level, club_position, @club_jersey_number, club_loaned_from, club_joined, 
    @club_contract_valid_until, nationality_id, nationality_name, @nation_team_id, nation_position, @nation_jersey_number, preferred_foot,
    weak_foot, skill_moves, international_reputation, work_rate, body_type, real_face, @release_clause_eur, player_tags, player_traits,
    @pace, @shooting, @passing, @dribbling, @defending, @physic, @attacking_crossing, @attacking_finishing, @attacking_heading_accuracy, 
    @attacking_short_passing, @attacking_volleys, @skill_dribbling, @skill_curve, @skill_fk_accuracy, @skill_long_passing, @skill_ball_control, 
    @movement_acceleration, @movement_sprint_speed, @movement_agility, @movement_reactions, @movement_balance, @power_shot_power, @power_jumping, 
    @power_stamina, @power_strength, @power_long_shots, @mentality_aggression, @mentality_interceptions, @mentality_positioning, @mentality_vision, 
    @mentality_penalties, @mentality_composure, @defending_marking_awareness, @defending_standing_tackle, @defending_sliding_tackle, @goalkeeping_diving, 
    @goalkeeping_handling, @goalkeeping_kicking, @goalkeeping_positioning, @goalkeeping_reflexes, @goalkeeping_speed, ls, st, rs, lw, lf, cf, rf, rw, lam, cam, ram, 
    lm, lcm, cm, rcm, rm, lwb, ldm, cdm, rdm, rwb, lb, lcb, cb, rcb, rb, gk, player_face_url,club_logo_url,club_flag_url,
    nation_logo_url, nation_flag_url)
    SET
		value_eur = NULLIF(@value_eur, ''),
        wage_eur = NULLIF(@wage_eur, ''),
        club_team_id = NULLIF(@club_team_id, ''),
        club_jersey_number = NULLIF(@club_jersey_number, ''),
        club_contract_valid_until = NULLIF(@club_contract_valid_until, ''),
		nation_team_id = NULLIF(@nation_team_id, ''),
        nation_jersey_number = NULLIF(@nation_jersey_number, ''),
        release_clause_eur = NULLIF(@release_clause_eur, ''),
        pace = NULLIF(@pace, ''), 
        shooting = NULLIF(@shooting, ''), 
        passing = NULLIF(@passing, ''), 
        dribbling = NULLIF(@dribbling, ''), 
        defending = NULLIF(@defending, ''), 
        physic = NULLIF(@physic, ''), 
        attacking_crossing = NULLIF(@attacking_crossing, ''), 
        attacking_finishing = NULLIF(@attacking_finishing, ''), 
        attacking_heading_accuracy = NULLIF(@attacking_heading_accuracy, ''), 
		attacking_short_passing = NULLIF(@attacking_short_passing, ''), 
        attacking_volleys = NULLIF(@attacking_volleys, ''), 
        skill_dribbling = NULLIF(@skill_dribbling, ''), 
        skill_curve = NULLIF(@skill_curve, ''), 
        skill_fk_accuracy = NULLIF(@skill_fk_accuracy, ''), 
        skill_long_passing = NULLIF(@skill_long_passing, ''), 
        skill_ball_control = NULLIF(@skill_ball_control, ''), 
		movement_acceleration = NULLIF(@movement_acceleration, ''), 
        movement_sprint_speed = NULLIF(@movement_sprint_speed, ''), 
        movement_agility = NULLIF(@movement_agility, ''), 
        movement_reactions = NULLIF(@movement_reactions, ''), 
        movement_balance = NULLIF(@movement_balance, ''), 
        power_shot_power = NULLIF(@power_shot_power, ''), 
        power_jumping = NULLIF(@power_jumping, ''), 
		power_stamina = NULLIF(@power_stamina, ''), 
        power_strength = NULLIF(@power_strength, ''), 
        power_long_shots = NULLIF(@power_long_shots, ''), 
        mentality_aggression = NULLIF(@mentality_aggression, ''), 
        mentality_interceptions = NULLIF(@mentality_interceptions, ''), 
        mentality_positioning = NULLIF(@mentality_positioning,''), 
        mentality_vision = NULLIF(@mentality_vision, ''), 
		mentality_penalties = NULLIF(@mentality_penalties, ''), 
        mentality_composure = NULLIF(@mentality_composure, ''), 
        defending_marking_awareness = NULLIF(@defending_marking_awareness, ''), 
        defending_standing_tackle = NULLIF(@defending_standing_tackle, ''), 
        defending_sliding_tackle = NULLIF(@defending_sliding_tackle, ''), 
        goalkeeping_diving = NULLIF(@goalkeeping_diving, ''), 
		goalkeeping_handling = NULLIF(@goalkeeping_handling, ''), 
        goalkeeping_kicking = NULLIF(@goalkeeping_kicking, ''), 
        goalkeeping_positioning = NULLIF(@goalkeeping_positioning, ''), 
        goalkeeping_reflexes = NULLIF(@goalkeeping_reflexes, ''), 
        goalkeeping_speed = NULLIF(@goalkeeping_speed, '');
        


-- Loading data from CSV file into mega table
LOAD DATA INFILE 'c:\\wamp64\\tmp\\fifaProj\\players_20.csv' INTO TABLE fifaData 
	FIELDS ENCLOSED BY '"' TERMINATED BY ','
	LINES TERMINATED BY '\n'
    IGNORE 1 ROWS
    
    (gender, fifaYear, sofifa_id, player_url, short_name, long_name, player_positions, overall, potential,@value_eur, @wage_eur, age, dob, height_cm, 
    weight_kg, @club_team_id, club_name, league_name, league_level, club_position, @club_jersey_number, club_loaned_from, club_joined, 
    @club_contract_valid_until, nationality_id, nationality_name, @nation_team_id, nation_position, @nation_jersey_number, preferred_foot,
    weak_foot, skill_moves, international_reputation, work_rate, body_type, real_face, @release_clause_eur, player_tags, player_traits,
    @pace, @shooting, @passing, @dribbling, @defending, @physic, @attacking_crossing, @attacking_finishing, @attacking_heading_accuracy, 
    @attacking_short_passing, @attacking_volleys, @skill_dribbling, @skill_curve, @skill_fk_accuracy, @skill_long_passing, @skill_ball_control, 
    @movement_acceleration, @movement_sprint_speed, @movement_agility, @movement_reactions, @movement_balance, @power_shot_power, @power_jumping, 
    @power_stamina, @power_strength, @power_long_shots, @mentality_aggression, @mentality_interceptions, @mentality_positioning, @mentality_vision, 
    @mentality_penalties, @mentality_composure, @defending_marking_awareness, @defending_standing_tackle, @defending_sliding_tackle, @goalkeeping_diving, 
    @goalkeeping_handling, @goalkeeping_kicking, @goalkeeping_positioning, @goalkeeping_reflexes, @goalkeeping_speed, ls, st, rs, lw, lf, cf, rf, rw, lam, cam, ram, 
    lm, lcm, cm, rcm, rm, lwb, ldm, cdm, rdm, rwb, lb, lcb, cb, rcb, rb, gk, player_face_url,club_logo_url,club_flag_url,
    nation_logo_url, nation_flag_url)
    SET
		value_eur = NULLIF(@value_eur, ''),
        wage_eur = NULLIF(@wage_eur, ''),
        club_team_id = NULLIF(@club_team_id, ''),
        club_jersey_number = NULLIF(@club_jersey_number, ''),
        club_contract_valid_until = NULLIF(@club_contract_valid_until, ''),
		nation_team_id = NULLIF(@nation_team_id, ''),
        nation_jersey_number = NULLIF(@nation_jersey_number, ''),
        release_clause_eur = NULLIF(@release_clause_eur, ''),
        pace = NULLIF(@pace, ''), 
        shooting = NULLIF(@shooting, ''), 
        passing = NULLIF(@passing, ''), 
        dribbling = NULLIF(@dribbling, ''), 
        defending = NULLIF(@defending, ''), 
        physic = NULLIF(@physic, ''), 
        attacking_crossing = NULLIF(@attacking_crossing, ''), 
        attacking_finishing = NULLIF(@attacking_finishing, ''), 
        attacking_heading_accuracy = NULLIF(@attacking_heading_accuracy, ''), 
		attacking_short_passing = NULLIF(@attacking_short_passing, ''), 
        attacking_volleys = NULLIF(@attacking_volleys, ''), 
        skill_dribbling = NULLIF(@skill_dribbling, ''), 
        skill_curve = NULLIF(@skill_curve, ''), 
        skill_fk_accuracy = NULLIF(@skill_fk_accuracy, ''), 
        skill_long_passing = NULLIF(@skill_long_passing, ''), 
        skill_ball_control = NULLIF(@skill_ball_control, ''), 
		movement_acceleration = NULLIF(@movement_acceleration, ''), 
        movement_sprint_speed = NULLIF(@movement_sprint_speed, ''), 
        movement_agility = NULLIF(@movement_agility, ''), 
        movement_reactions = NULLIF(@movement_reactions, ''), 
        movement_balance = NULLIF(@movement_balance, ''), 
        power_shot_power = NULLIF(@power_shot_power, ''), 
        power_jumping = NULLIF(@power_jumping, ''), 
		power_stamina = NULLIF(@power_stamina, ''), 
        power_strength = NULLIF(@power_strength, ''), 
        power_long_shots = NULLIF(@power_long_shots, ''), 
        mentality_aggression = NULLIF(@mentality_aggression, ''), 
        mentality_interceptions = NULLIF(@mentality_interceptions, ''), 
        mentality_positioning = NULLIF(@mentality_positioning,''), 
        mentality_vision = NULLIF(@mentality_vision, ''), 
		mentality_penalties = NULLIF(@mentality_penalties, ''), 
        mentality_composure = NULLIF(@mentality_composure, ''), 
        defending_marking_awareness = NULLIF(@defending_marking_awareness, ''), 
        defending_standing_tackle = NULLIF(@defending_standing_tackle, ''), 
        defending_sliding_tackle = NULLIF(@defending_sliding_tackle, ''), 
        goalkeeping_diving = NULLIF(@goalkeeping_diving, ''), 
		goalkeeping_handling = NULLIF(@goalkeeping_handling, ''), 
        goalkeeping_kicking = NULLIF(@goalkeeping_kicking, ''), 
        goalkeeping_positioning = NULLIF(@goalkeeping_positioning, ''), 
        goalkeeping_reflexes = NULLIF(@goalkeeping_reflexes, ''), 
        goalkeeping_speed = NULLIF(@goalkeeping_speed, '');
        
        
        
-- Loading data from CSV file into mega table
LOAD DATA INFILE 'c:\\wamp64\\tmp\\fifaProj\\female_players_20.csv' INTO TABLE fifaData 
	FIELDS ENCLOSED BY '"' TERMINATED BY ','
	LINES TERMINATED BY '\n'
    IGNORE 1 ROWS
    
    (gender, fifaYear, sofifa_id, player_url, short_name, long_name, player_positions, overall, potential,@value_eur, @wage_eur, age, dob, height_cm, 
    weight_kg, @club_team_id, club_name, league_name, league_level, club_position, @club_jersey_number, club_loaned_from, club_joined, 
    @club_contract_valid_until, nationality_id, nationality_name, @nation_team_id, nation_position, @nation_jersey_number, preferred_foot,
    weak_foot, skill_moves, international_reputation, work_rate, body_type, real_face, @release_clause_eur, player_tags, player_traits,
    @pace, @shooting, @passing, @dribbling, @defending, @physic, @attacking_crossing, @attacking_finishing, @attacking_heading_accuracy, 
    @attacking_short_passing, @attacking_volleys, @skill_dribbling, @skill_curve, @skill_fk_accuracy, @skill_long_passing, @skill_ball_control, 
    @movement_acceleration, @movement_sprint_speed, @movement_agility, @movement_reactions, @movement_balance, @power_shot_power, @power_jumping, 
    @power_stamina, @power_strength, @power_long_shots, @mentality_aggression, @mentality_interceptions, @mentality_positioning, @mentality_vision, 
    @mentality_penalties, @mentality_composure, @defending_marking_awareness, @defending_standing_tackle, @defending_sliding_tackle, @goalkeeping_diving, 
    @goalkeeping_handling, @goalkeeping_kicking, @goalkeeping_positioning, @goalkeeping_reflexes, @goalkeeping_speed, ls, st, rs, lw, lf, cf, rf, rw, lam, cam, ram, 
    lm, lcm, cm, rcm, rm, lwb, ldm, cdm, rdm, rwb, lb, lcb, cb, rcb, rb, gk, player_face_url,club_logo_url,club_flag_url,
    nation_logo_url, nation_flag_url)
    SET
		value_eur = NULLIF(@value_eur, ''),
        wage_eur = NULLIF(@wage_eur, ''),
        club_team_id = NULLIF(@club_team_id, ''),
        club_jersey_number = NULLIF(@club_jersey_number, ''),
        club_contract_valid_until = NULLIF(@club_contract_valid_until, ''),
		nation_team_id = NULLIF(@nation_team_id, ''),
        nation_jersey_number = NULLIF(@nation_jersey_number, ''),
        release_clause_eur = NULLIF(@release_clause_eur, ''),
        pace = NULLIF(@pace, ''), 
        shooting = NULLIF(@shooting, ''), 
        passing = NULLIF(@passing, ''), 
        dribbling = NULLIF(@dribbling, ''), 
        defending = NULLIF(@defending, ''), 
        physic = NULLIF(@physic, ''), 
        attacking_crossing = NULLIF(@attacking_crossing, ''), 
        attacking_finishing = NULLIF(@attacking_finishing, ''), 
        attacking_heading_accuracy = NULLIF(@attacking_heading_accuracy, ''), 
		attacking_short_passing = NULLIF(@attacking_short_passing, ''), 
        attacking_volleys = NULLIF(@attacking_volleys, ''), 
        skill_dribbling = NULLIF(@skill_dribbling, ''), 
        skill_curve = NULLIF(@skill_curve, ''), 
        skill_fk_accuracy = NULLIF(@skill_fk_accuracy, ''), 
        skill_long_passing = NULLIF(@skill_long_passing, ''), 
        skill_ball_control = NULLIF(@skill_ball_control, ''), 
		movement_acceleration = NULLIF(@movement_acceleration, ''), 
        movement_sprint_speed = NULLIF(@movement_sprint_speed, ''), 
        movement_agility = NULLIF(@movement_agility, ''), 
        movement_reactions = NULLIF(@movement_reactions, ''), 
        movement_balance = NULLIF(@movement_balance, ''), 
        power_shot_power = NULLIF(@power_shot_power, ''), 
        power_jumping = NULLIF(@power_jumping, ''), 
		power_stamina = NULLIF(@power_stamina, ''), 
        power_strength = NULLIF(@power_strength, ''), 
        power_long_shots = NULLIF(@power_long_shots, ''), 
        mentality_aggression = NULLIF(@mentality_aggression, ''), 
        mentality_interceptions = NULLIF(@mentality_interceptions, ''), 
        mentality_positioning = NULLIF(@mentality_positioning,''), 
        mentality_vision = NULLIF(@mentality_vision, ''), 
		mentality_penalties = NULLIF(@mentality_penalties, ''), 
        mentality_composure = NULLIF(@mentality_composure, ''), 
        defending_marking_awareness = NULLIF(@defending_marking_awareness, ''), 
        defending_standing_tackle = NULLIF(@defending_standing_tackle, ''), 
        defending_sliding_tackle = NULLIF(@defending_sliding_tackle, ''), 
        goalkeeping_diving = NULLIF(@goalkeeping_diving, ''), 
		goalkeeping_handling = NULLIF(@goalkeeping_handling, ''), 
        goalkeeping_kicking = NULLIF(@goalkeeping_kicking, ''), 
        goalkeeping_positioning = NULLIF(@goalkeeping_positioning, ''), 
        goalkeeping_reflexes = NULLIF(@goalkeeping_reflexes, ''), 
        goalkeeping_speed = NULLIF(@goalkeeping_speed, '');


-- Loading data from CSV file into mega table
LOAD DATA INFILE 'c:\\wamp64\\tmp\\fifaProj\\players_19.csv' INTO TABLE fifaData 
	FIELDS ENCLOSED BY '"' TERMINATED BY ','
	LINES TERMINATED BY '\n'
    IGNORE 1 ROWS
    
    (gender, fifaYear, sofifa_id, player_url, short_name, long_name, player_positions, overall, potential,@value_eur, @wage_eur, age, dob, height_cm, 
    weight_kg, @club_team_id, club_name, league_name, league_level, club_position, @club_jersey_number, club_loaned_from, club_joined, 
    @club_contract_valid_until, nationality_id, nationality_name, @nation_team_id, nation_position, @nation_jersey_number, preferred_foot,
    weak_foot, skill_moves, international_reputation, work_rate, body_type, real_face, @release_clause_eur, player_tags, player_traits,
    @pace, @shooting, @passing, @dribbling, @defending, @physic, @attacking_crossing, @attacking_finishing, @attacking_heading_accuracy, 
    @attacking_short_passing, @attacking_volleys, @skill_dribbling, @skill_curve, @skill_fk_accuracy, @skill_long_passing, @skill_ball_control, 
    @movement_acceleration, @movement_sprint_speed, @movement_agility, @movement_reactions, @movement_balance, @power_shot_power, @power_jumping, 
    @power_stamina, @power_strength, @power_long_shots, @mentality_aggression, @mentality_interceptions, @mentality_positioning, @mentality_vision, 
    @mentality_penalties, @mentality_composure, @defending_marking_awareness, @defending_standing_tackle, @defending_sliding_tackle, @goalkeeping_diving, 
    @goalkeeping_handling, @goalkeeping_kicking, @goalkeeping_positioning, @goalkeeping_reflexes, @goalkeeping_speed, ls, st, rs, lw, lf, cf, rf, rw, lam, cam, ram, 
    lm, lcm, cm, rcm, rm, lwb, ldm, cdm, rdm, rwb, lb, lcb, cb, rcb, rb, gk, player_face_url,club_logo_url,club_flag_url,
    nation_logo_url, nation_flag_url)
    SET
		value_eur = NULLIF(@value_eur, ''),
        wage_eur = NULLIF(@wage_eur, ''),
        club_team_id = NULLIF(@club_team_id, ''),
        club_jersey_number = NULLIF(@club_jersey_number, ''),
        club_contract_valid_until = NULLIF(@club_contract_valid_until, ''),
		nation_team_id = NULLIF(@nation_team_id, ''),
        nation_jersey_number = NULLIF(@nation_jersey_number, ''),
        release_clause_eur = NULLIF(@release_clause_eur, ''),
        pace = NULLIF(@pace, ''), 
        shooting = NULLIF(@shooting, ''), 
        passing = NULLIF(@passing, ''), 
        dribbling = NULLIF(@dribbling, ''), 
        defending = NULLIF(@defending, ''), 
        physic = NULLIF(@physic, ''), 
        attacking_crossing = NULLIF(@attacking_crossing, ''), 
        attacking_finishing = NULLIF(@attacking_finishing, ''), 
        attacking_heading_accuracy = NULLIF(@attacking_heading_accuracy, ''), 
		attacking_short_passing = NULLIF(@attacking_short_passing, ''), 
        attacking_volleys = NULLIF(@attacking_volleys, ''), 
        skill_dribbling = NULLIF(@skill_dribbling, ''), 
        skill_curve = NULLIF(@skill_curve, ''), 
        skill_fk_accuracy = NULLIF(@skill_fk_accuracy, ''), 
        skill_long_passing = NULLIF(@skill_long_passing, ''), 
        skill_ball_control = NULLIF(@skill_ball_control, ''), 
		movement_acceleration = NULLIF(@movement_acceleration, ''), 
        movement_sprint_speed = NULLIF(@movement_sprint_speed, ''), 
        movement_agility = NULLIF(@movement_agility, ''), 
        movement_reactions = NULLIF(@movement_reactions, ''), 
        movement_balance = NULLIF(@movement_balance, ''), 
        power_shot_power = NULLIF(@power_shot_power, ''), 
        power_jumping = NULLIF(@power_jumping, ''), 
		power_stamina = NULLIF(@power_stamina, ''), 
        power_strength = NULLIF(@power_strength, ''), 
        power_long_shots = NULLIF(@power_long_shots, ''), 
        mentality_aggression = NULLIF(@mentality_aggression, ''), 
        mentality_interceptions = NULLIF(@mentality_interceptions, ''), 
        mentality_positioning = NULLIF(@mentality_positioning,''), 
        mentality_vision = NULLIF(@mentality_vision, ''), 
		mentality_penalties = NULLIF(@mentality_penalties, ''), 
        mentality_composure = NULLIF(@mentality_composure, ''), 
        defending_marking_awareness = NULLIF(@defending_marking_awareness, ''), 
        defending_standing_tackle = NULLIF(@defending_standing_tackle, ''), 
        defending_sliding_tackle = NULLIF(@defending_sliding_tackle, ''), 
        goalkeeping_diving = NULLIF(@goalkeeping_diving, ''), 
		goalkeeping_handling = NULLIF(@goalkeeping_handling, ''), 
        goalkeeping_kicking = NULLIF(@goalkeeping_kicking, ''), 
        goalkeeping_positioning = NULLIF(@goalkeeping_positioning, ''), 
        goalkeeping_reflexes = NULLIF(@goalkeeping_reflexes, ''), 
        goalkeeping_speed = NULLIF(@goalkeeping_speed, '');





-- Loading data from CSV file into mega table
LOAD DATA INFILE 'c:\\wamp64\\tmp\\fifaProj\\female_players_19.csv' INTO TABLE fifaData 
	FIELDS ENCLOSED BY '"' TERMINATED BY ','
	LINES TERMINATED BY '\n'
    IGNORE 1 ROWS
    
    (gender, fifaYear, sofifa_id, player_url, short_name, long_name, player_positions, overall, potential,@value_eur, @wage_eur, age, dob, height_cm, 
    weight_kg, @club_team_id, club_name, league_name, league_level, club_position, @club_jersey_number, club_loaned_from, club_joined, 
    @club_contract_valid_until, nationality_id, nationality_name, @nation_team_id, nation_position, @nation_jersey_number, preferred_foot,
    weak_foot, skill_moves, international_reputation, work_rate, body_type, real_face, @release_clause_eur, player_tags, player_traits,
    @pace, @shooting, @passing, @dribbling, @defending, @physic, @attacking_crossing, @attacking_finishing, @attacking_heading_accuracy, 
    @attacking_short_passing, @attacking_volleys, @skill_dribbling, @skill_curve, @skill_fk_accuracy, @skill_long_passing, @skill_ball_control, 
    @movement_acceleration, @movement_sprint_speed, @movement_agility, @movement_reactions, @movement_balance, @power_shot_power, @power_jumping, 
    @power_stamina, @power_strength, @power_long_shots, @mentality_aggression, @mentality_interceptions, @mentality_positioning, @mentality_vision, 
    @mentality_penalties, @mentality_composure, @defending_marking_awareness, @defending_standing_tackle, @defending_sliding_tackle, @goalkeeping_diving, 
    @goalkeeping_handling, @goalkeeping_kicking, @goalkeeping_positioning, @goalkeeping_reflexes, @goalkeeping_speed, ls, st, rs, lw, lf, cf, rf, rw, lam, cam, ram, 
    lm, lcm, cm, rcm, rm, lwb, ldm, cdm, rdm, rwb, lb, lcb, cb, rcb, rb, gk, player_face_url,club_logo_url,club_flag_url,
    nation_logo_url, nation_flag_url)
    SET
		value_eur = NULLIF(@value_eur, ''),
        wage_eur = NULLIF(@wage_eur, ''),
        club_team_id = NULLIF(@club_team_id, ''),
        club_jersey_number = NULLIF(@club_jersey_number, ''),
        club_contract_valid_until = NULLIF(@club_contract_valid_until, ''),
		nation_team_id = NULLIF(@nation_team_id, ''),
        nation_jersey_number = NULLIF(@nation_jersey_number, ''),
        release_clause_eur = NULLIF(@release_clause_eur, ''),
        pace = NULLIF(@pace, ''), 
        shooting = NULLIF(@shooting, ''), 
        passing = NULLIF(@passing, ''), 
        dribbling = NULLIF(@dribbling, ''), 
        defending = NULLIF(@defending, ''), 
        physic = NULLIF(@physic, ''), 
        attacking_crossing = NULLIF(@attacking_crossing, ''), 
        attacking_finishing = NULLIF(@attacking_finishing, ''), 
        attacking_heading_accuracy = NULLIF(@attacking_heading_accuracy, ''), 
		attacking_short_passing = NULLIF(@attacking_short_passing, ''), 
        attacking_volleys = NULLIF(@attacking_volleys, ''), 
        skill_dribbling = NULLIF(@skill_dribbling, ''), 
        skill_curve = NULLIF(@skill_curve, ''), 
        skill_fk_accuracy = NULLIF(@skill_fk_accuracy, ''), 
        skill_long_passing = NULLIF(@skill_long_passing, ''), 
        skill_ball_control = NULLIF(@skill_ball_control, ''), 
		movement_acceleration = NULLIF(@movement_acceleration, ''), 
        movement_sprint_speed = NULLIF(@movement_sprint_speed, ''), 
        movement_agility = NULLIF(@movement_agility, ''), 
        movement_reactions = NULLIF(@movement_reactions, ''), 
        movement_balance = NULLIF(@movement_balance, ''), 
        power_shot_power = NULLIF(@power_shot_power, ''), 
        power_jumping = NULLIF(@power_jumping, ''), 
		power_stamina = NULLIF(@power_stamina, ''), 
        power_strength = NULLIF(@power_strength, ''), 
        power_long_shots = NULLIF(@power_long_shots, ''), 
        mentality_aggression = NULLIF(@mentality_aggression, ''), 
        mentality_interceptions = NULLIF(@mentality_interceptions, ''), 
        mentality_positioning = NULLIF(@mentality_positioning,''), 
        mentality_vision = NULLIF(@mentality_vision, ''), 
		mentality_penalties = NULLIF(@mentality_penalties, ''), 
        mentality_composure = NULLIF(@mentality_composure, ''), 
        defending_marking_awareness = NULLIF(@defending_marking_awareness, ''), 
        defending_standing_tackle = NULLIF(@defending_standing_tackle, ''), 
        defending_sliding_tackle = NULLIF(@defending_sliding_tackle, ''), 
        goalkeeping_diving = NULLIF(@goalkeeping_diving, ''), 
		goalkeeping_handling = NULLIF(@goalkeeping_handling, ''), 
        goalkeeping_kicking = NULLIF(@goalkeeping_kicking, ''), 
        goalkeeping_positioning = NULLIF(@goalkeeping_positioning, ''), 
        goalkeeping_reflexes = NULLIF(@goalkeeping_reflexes, ''), 
        goalkeeping_speed = NULLIF(@goalkeeping_speed, '');



-- Loading data from CSV file into mega table
LOAD DATA INFILE 'c:\\wamp64\\tmp\\fifaProj\\players_18.csv' INTO TABLE fifaData 
	FIELDS ENCLOSED BY '"' TERMINATED BY ','
	LINES TERMINATED BY '\n'
    IGNORE 1 ROWS
    
    (gender, fifaYear, sofifa_id, player_url, short_name, long_name, player_positions, overall, potential,@value_eur, @wage_eur, age, dob, height_cm, 
    weight_kg, @club_team_id, club_name, league_name, league_level, club_position, @club_jersey_number, club_loaned_from, club_joined, 
    @club_contract_valid_until, nationality_id, nationality_name, @nation_team_id, nation_position, @nation_jersey_number, preferred_foot,
    weak_foot, skill_moves, international_reputation, work_rate, body_type, real_face, @release_clause_eur, player_tags, player_traits,
    @pace, @shooting, @passing, @dribbling, @defending, @physic, @attacking_crossing, @attacking_finishing, @attacking_heading_accuracy, 
    @attacking_short_passing, @attacking_volleys, @skill_dribbling, @skill_curve, @skill_fk_accuracy, @skill_long_passing, @skill_ball_control, 
    @movement_acceleration, @movement_sprint_speed, @movement_agility, @movement_reactions, @movement_balance, @power_shot_power, @power_jumping, 
    @power_stamina, @power_strength, @power_long_shots, @mentality_aggression, @mentality_interceptions, @mentality_positioning, @mentality_vision, 
    @mentality_penalties, @mentality_composure, @defending_marking_awareness, @defending_standing_tackle, @defending_sliding_tackle, @goalkeeping_diving, 
    @goalkeeping_handling, @goalkeeping_kicking, @goalkeeping_positioning, @goalkeeping_reflexes, @goalkeeping_speed, ls, st, rs, lw, lf, cf, rf, rw, lam, cam, ram, 
    lm, lcm, cm, rcm, rm, lwb, ldm, cdm, rdm, rwb, lb, lcb, cb, rcb, rb, gk, player_face_url,club_logo_url,club_flag_url,
    nation_logo_url, nation_flag_url)
    SET
		value_eur = NULLIF(@value_eur, ''),
        wage_eur = NULLIF(@wage_eur, ''),
        club_team_id = NULLIF(@club_team_id, ''),
        club_jersey_number = NULLIF(@club_jersey_number, ''),
        club_contract_valid_until = NULLIF(@club_contract_valid_until, ''),
		nation_team_id = NULLIF(@nation_team_id, ''),
        nation_jersey_number = NULLIF(@nation_jersey_number, ''),
        release_clause_eur = NULLIF(@release_clause_eur, ''),
        pace = NULLIF(@pace, ''), 
        shooting = NULLIF(@shooting, ''), 
        passing = NULLIF(@passing, ''), 
        dribbling = NULLIF(@dribbling, ''), 
        defending = NULLIF(@defending, ''), 
        physic = NULLIF(@physic, ''), 
        attacking_crossing = NULLIF(@attacking_crossing, ''), 
        attacking_finishing = NULLIF(@attacking_finishing, ''), 
        attacking_heading_accuracy = NULLIF(@attacking_heading_accuracy, ''), 
		attacking_short_passing = NULLIF(@attacking_short_passing, ''), 
        attacking_volleys = NULLIF(@attacking_volleys, ''), 
        skill_dribbling = NULLIF(@skill_dribbling, ''), 
        skill_curve = NULLIF(@skill_curve, ''), 
        skill_fk_accuracy = NULLIF(@skill_fk_accuracy, ''), 
        skill_long_passing = NULLIF(@skill_long_passing, ''), 
        skill_ball_control = NULLIF(@skill_ball_control, ''), 
		movement_acceleration = NULLIF(@movement_acceleration, ''), 
        movement_sprint_speed = NULLIF(@movement_sprint_speed, ''), 
        movement_agility = NULLIF(@movement_agility, ''), 
        movement_reactions = NULLIF(@movement_reactions, ''), 
        movement_balance = NULLIF(@movement_balance, ''), 
        power_shot_power = NULLIF(@power_shot_power, ''), 
        power_jumping = NULLIF(@power_jumping, ''), 
		power_stamina = NULLIF(@power_stamina, ''), 
        power_strength = NULLIF(@power_strength, ''), 
        power_long_shots = NULLIF(@power_long_shots, ''), 
        mentality_aggression = NULLIF(@mentality_aggression, ''), 
        mentality_interceptions = NULLIF(@mentality_interceptions, ''), 
        mentality_positioning = NULLIF(@mentality_positioning,''), 
        mentality_vision = NULLIF(@mentality_vision, ''), 
		mentality_penalties = NULLIF(@mentality_penalties, ''), 
        mentality_composure = NULLIF(@mentality_composure, ''), 
        defending_marking_awareness = NULLIF(@defending_marking_awareness, ''), 
        defending_standing_tackle = NULLIF(@defending_standing_tackle, ''), 
        defending_sliding_tackle = NULLIF(@defending_sliding_tackle, ''), 
        goalkeeping_diving = NULLIF(@goalkeeping_diving, ''), 
		goalkeeping_handling = NULLIF(@goalkeeping_handling, ''), 
        goalkeeping_kicking = NULLIF(@goalkeeping_kicking, ''), 
        goalkeeping_positioning = NULLIF(@goalkeeping_positioning, ''), 
        goalkeeping_reflexes = NULLIF(@goalkeeping_reflexes, ''), 
        goalkeeping_speed = NULLIF(@goalkeeping_speed, '');



-- Loading data from CSV file into mega table
LOAD DATA INFILE 'c:\\wamp64\\tmp\\fifaProj\\female_players_18.csv' INTO TABLE fifaData 
	FIELDS ENCLOSED BY '"' TERMINATED BY ','
	LINES TERMINATED BY '\n'
    IGNORE 1 ROWS
    
    (gender, fifaYear, sofifa_id, player_url, short_name, long_name, player_positions, overall, potential,@value_eur, @wage_eur, age, dob, height_cm, 
    weight_kg, @club_team_id, club_name, league_name, league_level, club_position, @club_jersey_number, club_loaned_from, club_joined, 
    @club_contract_valid_until, nationality_id, nationality_name, @nation_team_id, nation_position, @nation_jersey_number, preferred_foot,
    weak_foot, skill_moves, international_reputation, work_rate, body_type, real_face, @release_clause_eur, player_tags, player_traits,
    @pace, @shooting, @passing, @dribbling, @defending, @physic, @attacking_crossing, @attacking_finishing, @attacking_heading_accuracy, 
    @attacking_short_passing, @attacking_volleys, @skill_dribbling, @skill_curve, @skill_fk_accuracy, @skill_long_passing, @skill_ball_control, 
    @movement_acceleration, @movement_sprint_speed, @movement_agility, @movement_reactions, @movement_balance, @power_shot_power, @power_jumping, 
    @power_stamina, @power_strength, @power_long_shots, @mentality_aggression, @mentality_interceptions, @mentality_positioning, @mentality_vision, 
    @mentality_penalties, @mentality_composure, @defending_marking_awareness, @defending_standing_tackle, @defending_sliding_tackle, @goalkeeping_diving, 
    @goalkeeping_handling, @goalkeeping_kicking, @goalkeeping_positioning, @goalkeeping_reflexes, @goalkeeping_speed, ls, st, rs, lw, lf, cf, rf, rw, lam, cam, ram, 
    lm, lcm, cm, rcm, rm, lwb, ldm, cdm, rdm, rwb, lb, lcb, cb, rcb, rb, gk, player_face_url,club_logo_url,club_flag_url,
    nation_logo_url, nation_flag_url)
    SET
		value_eur = NULLIF(@value_eur, ''),
        wage_eur = NULLIF(@wage_eur, ''),
        club_team_id = NULLIF(@club_team_id, ''),
        club_jersey_number = NULLIF(@club_jersey_number, ''),
        club_contract_valid_until = NULLIF(@club_contract_valid_until, ''),
		nation_team_id = NULLIF(@nation_team_id, ''),
        nation_jersey_number = NULLIF(@nation_jersey_number, ''),
        release_clause_eur = NULLIF(@release_clause_eur, ''),
        pace = NULLIF(@pace, ''), 
        shooting = NULLIF(@shooting, ''), 
        passing = NULLIF(@passing, ''), 
        dribbling = NULLIF(@dribbling, ''), 
        defending = NULLIF(@defending, ''), 
        physic = NULLIF(@physic, ''), 
        attacking_crossing = NULLIF(@attacking_crossing, ''), 
        attacking_finishing = NULLIF(@attacking_finishing, ''), 
        attacking_heading_accuracy = NULLIF(@attacking_heading_accuracy, ''), 
		attacking_short_passing = NULLIF(@attacking_short_passing, ''), 
        attacking_volleys = NULLIF(@attacking_volleys, ''), 
        skill_dribbling = NULLIF(@skill_dribbling, ''), 
        skill_curve = NULLIF(@skill_curve, ''), 
        skill_fk_accuracy = NULLIF(@skill_fk_accuracy, ''), 
        skill_long_passing = NULLIF(@skill_long_passing, ''), 
        skill_ball_control = NULLIF(@skill_ball_control, ''), 
		movement_acceleration = NULLIF(@movement_acceleration, ''), 
        movement_sprint_speed = NULLIF(@movement_sprint_speed, ''), 
        movement_agility = NULLIF(@movement_agility, ''), 
        movement_reactions = NULLIF(@movement_reactions, ''), 
        movement_balance = NULLIF(@movement_balance, ''), 
        power_shot_power = NULLIF(@power_shot_power, ''), 
        power_jumping = NULLIF(@power_jumping, ''), 
		power_stamina = NULLIF(@power_stamina, ''), 
        power_strength = NULLIF(@power_strength, ''), 
        power_long_shots = NULLIF(@power_long_shots, ''), 
        mentality_aggression = NULLIF(@mentality_aggression, ''), 
        mentality_interceptions = NULLIF(@mentality_interceptions, ''), 
        mentality_positioning = NULLIF(@mentality_positioning,''), 
        mentality_vision = NULLIF(@mentality_vision, ''), 
		mentality_penalties = NULLIF(@mentality_penalties, ''), 
        mentality_composure = NULLIF(@mentality_composure, ''), 
        defending_marking_awareness = NULLIF(@defending_marking_awareness, ''), 
        defending_standing_tackle = NULLIF(@defending_standing_tackle, ''), 
        defending_sliding_tackle = NULLIF(@defending_sliding_tackle, ''), 
        goalkeeping_diving = NULLIF(@goalkeeping_diving, ''), 
		goalkeeping_handling = NULLIF(@goalkeeping_handling, ''), 
        goalkeeping_kicking = NULLIF(@goalkeeping_kicking, ''), 
        goalkeeping_positioning = NULLIF(@goalkeeping_positioning, ''), 
        goalkeeping_reflexes = NULLIF(@goalkeeping_reflexes, ''), 
        goalkeeping_speed = NULLIF(@goalkeeping_speed, '');





-- Loading data from CSV file into mega table
LOAD DATA INFILE 'c:\\wamp64\\tmp\\fifaProj\\players_17.csv' INTO TABLE fifaData 
	FIELDS ENCLOSED BY '"' TERMINATED BY ','
	LINES TERMINATED BY '\n'
    IGNORE 1 ROWS
    
    (gender, fifaYear, sofifa_id, player_url, short_name, long_name, player_positions, overall, potential,@value_eur, @wage_eur, age, dob, height_cm, 
    weight_kg, @club_team_id, club_name, league_name, league_level, club_position, @club_jersey_number, club_loaned_from, club_joined, 
    @club_contract_valid_until, nationality_id, nationality_name, @nation_team_id, nation_position, @nation_jersey_number, preferred_foot,
    weak_foot, skill_moves, international_reputation, work_rate, body_type, real_face, @release_clause_eur, player_tags, player_traits,
    @pace, @shooting, @passing, @dribbling, @defending, @physic, @attacking_crossing, @attacking_finishing, @attacking_heading_accuracy, 
    @attacking_short_passing, @attacking_volleys, @skill_dribbling, @skill_curve, @skill_fk_accuracy, @skill_long_passing, @skill_ball_control, 
    @movement_acceleration, @movement_sprint_speed, @movement_agility, @movement_reactions, @movement_balance, @power_shot_power, @power_jumping, 
    @power_stamina, @power_strength, @power_long_shots, @mentality_aggression, @mentality_interceptions, @mentality_positioning, @mentality_vision, 
    @mentality_penalties, @mentality_composure, @defending_marking_awareness, @defending_standing_tackle, @defending_sliding_tackle, @goalkeeping_diving, 
    @goalkeeping_handling, @goalkeeping_kicking, @goalkeeping_positioning, @goalkeeping_reflexes, @goalkeeping_speed, ls, st, rs, lw, lf, cf, rf, rw, lam, cam, ram, 
    lm, lcm, cm, rcm, rm, lwb, ldm, cdm, rdm, rwb, lb, lcb, cb, rcb, rb, gk, player_face_url,club_logo_url,club_flag_url,
    nation_logo_url, nation_flag_url)
    SET
		value_eur = NULLIF(@value_eur, ''),
        wage_eur = NULLIF(@wage_eur, ''),
        club_team_id = NULLIF(@club_team_id, ''),
        club_jersey_number = NULLIF(@club_jersey_number, ''),
        club_contract_valid_until = NULLIF(@club_contract_valid_until, ''),
		nation_team_id = NULLIF(@nation_team_id, ''),
        nation_jersey_number = NULLIF(@nation_jersey_number, ''),
        release_clause_eur = NULLIF(@release_clause_eur, ''),
        pace = NULLIF(@pace, ''), 
        shooting = NULLIF(@shooting, ''), 
        passing = NULLIF(@passing, ''), 
        dribbling = NULLIF(@dribbling, ''), 
        defending = NULLIF(@defending, ''), 
        physic = NULLIF(@physic, ''), 
        attacking_crossing = NULLIF(@attacking_crossing, ''), 
        attacking_finishing = NULLIF(@attacking_finishing, ''), 
        attacking_heading_accuracy = NULLIF(@attacking_heading_accuracy, ''), 
		attacking_short_passing = NULLIF(@attacking_short_passing, ''), 
        attacking_volleys = NULLIF(@attacking_volleys, ''), 
        skill_dribbling = NULLIF(@skill_dribbling, ''), 
        skill_curve = NULLIF(@skill_curve, ''), 
        skill_fk_accuracy = NULLIF(@skill_fk_accuracy, ''), 
        skill_long_passing = NULLIF(@skill_long_passing, ''), 
        skill_ball_control = NULLIF(@skill_ball_control, ''), 
		movement_acceleration = NULLIF(@movement_acceleration, ''), 
        movement_sprint_speed = NULLIF(@movement_sprint_speed, ''), 
        movement_agility = NULLIF(@movement_agility, ''), 
        movement_reactions = NULLIF(@movement_reactions, ''), 
        movement_balance = NULLIF(@movement_balance, ''), 
        power_shot_power = NULLIF(@power_shot_power, ''), 
        power_jumping = NULLIF(@power_jumping, ''), 
		power_stamina = NULLIF(@power_stamina, ''), 
        power_strength = NULLIF(@power_strength, ''), 
        power_long_shots = NULLIF(@power_long_shots, ''), 
        mentality_aggression = NULLIF(@mentality_aggression, ''), 
        mentality_interceptions = NULLIF(@mentality_interceptions, ''), 
        mentality_positioning = NULLIF(@mentality_positioning,''), 
        mentality_vision = NULLIF(@mentality_vision, ''), 
		mentality_penalties = NULLIF(@mentality_penalties, ''), 
        mentality_composure = NULLIF(@mentality_composure, ''), 
        defending_marking_awareness = NULLIF(@defending_marking_awareness, ''), 
        defending_standing_tackle = NULLIF(@defending_standing_tackle, ''), 
        defending_sliding_tackle = NULLIF(@defending_sliding_tackle, ''), 
        goalkeeping_diving = NULLIF(@goalkeeping_diving, ''), 
		goalkeeping_handling = NULLIF(@goalkeeping_handling, ''), 
        goalkeeping_kicking = NULLIF(@goalkeeping_kicking, ''), 
        goalkeeping_positioning = NULLIF(@goalkeeping_positioning, ''), 
        goalkeeping_reflexes = NULLIF(@goalkeeping_reflexes, ''), 
        goalkeeping_speed = NULLIF(@goalkeeping_speed, '');




-- Loading data from CSV file into mega table
LOAD DATA INFILE 'c:\\wamp64\\tmp\\fifaProj\\female_players_17.csv' INTO TABLE fifaData 
	FIELDS ENCLOSED BY '"' TERMINATED BY ','
	LINES TERMINATED BY '\n'
    IGNORE 1 ROWS
    
    (gender, fifaYear, sofifa_id, player_url, short_name, long_name, player_positions, overall, potential,@value_eur, @wage_eur, age, dob, height_cm, 
    weight_kg, @club_team_id, club_name, league_name, league_level, club_position, @club_jersey_number, club_loaned_from, club_joined, 
    @club_contract_valid_until, nationality_id, nationality_name, @nation_team_id, nation_position, @nation_jersey_number, preferred_foot,
    weak_foot, skill_moves, international_reputation, work_rate, body_type, real_face, @release_clause_eur, player_tags, player_traits,
    @pace, @shooting, @passing, @dribbling, @defending, @physic, @attacking_crossing, @attacking_finishing, @attacking_heading_accuracy, 
    @attacking_short_passing, @attacking_volleys, @skill_dribbling, @skill_curve, @skill_fk_accuracy, @skill_long_passing, @skill_ball_control, 
    @movement_acceleration, @movement_sprint_speed, @movement_agility, @movement_reactions, @movement_balance, @power_shot_power, @power_jumping, 
    @power_stamina, @power_strength, @power_long_shots, @mentality_aggression, @mentality_interceptions, @mentality_positioning, @mentality_vision, 
    @mentality_penalties, @mentality_composure, @defending_marking_awareness, @defending_standing_tackle, @defending_sliding_tackle, @goalkeeping_diving, 
    @goalkeeping_handling, @goalkeeping_kicking, @goalkeeping_positioning, @goalkeeping_reflexes, @goalkeeping_speed, ls, st, rs, lw, lf, cf, rf, rw, lam, cam, ram, 
    lm, lcm, cm, rcm, rm, lwb, ldm, cdm, rdm, rwb, lb, lcb, cb, rcb, rb, gk, player_face_url,club_logo_url,club_flag_url,
    nation_logo_url, nation_flag_url)
    SET
		value_eur = NULLIF(@value_eur, ''),
        wage_eur = NULLIF(@wage_eur, ''),
        club_team_id = NULLIF(@club_team_id, ''),
        club_jersey_number = NULLIF(@club_jersey_number, ''),
        club_contract_valid_until = NULLIF(@club_contract_valid_until, ''),
		nation_team_id = NULLIF(@nation_team_id, ''),
        nation_jersey_number = NULLIF(@nation_jersey_number, ''),
        release_clause_eur = NULLIF(@release_clause_eur, ''),
        pace = NULLIF(@pace, ''), 
        shooting = NULLIF(@shooting, ''), 
        passing = NULLIF(@passing, ''), 
        dribbling = NULLIF(@dribbling, ''), 
        defending = NULLIF(@defending, ''), 
        physic = NULLIF(@physic, ''), 
        attacking_crossing = NULLIF(@attacking_crossing, ''), 
        attacking_finishing = NULLIF(@attacking_finishing, ''), 
        attacking_heading_accuracy = NULLIF(@attacking_heading_accuracy, ''), 
		attacking_short_passing = NULLIF(@attacking_short_passing, ''), 
        attacking_volleys = NULLIF(@attacking_volleys, ''), 
        skill_dribbling = NULLIF(@skill_dribbling, ''), 
        skill_curve = NULLIF(@skill_curve, ''), 
        skill_fk_accuracy = NULLIF(@skill_fk_accuracy, ''), 
        skill_long_passing = NULLIF(@skill_long_passing, ''), 
        skill_ball_control = NULLIF(@skill_ball_control, ''), 
		movement_acceleration = NULLIF(@movement_acceleration, ''), 
        movement_sprint_speed = NULLIF(@movement_sprint_speed, ''), 
        movement_agility = NULLIF(@movement_agility, ''), 
        movement_reactions = NULLIF(@movement_reactions, ''), 
        movement_balance = NULLIF(@movement_balance, ''), 
        power_shot_power = NULLIF(@power_shot_power, ''), 
        power_jumping = NULLIF(@power_jumping, ''), 
		power_stamina = NULLIF(@power_stamina, ''), 
        power_strength = NULLIF(@power_strength, ''), 
        power_long_shots = NULLIF(@power_long_shots, ''), 
        mentality_aggression = NULLIF(@mentality_aggression, ''), 
        mentality_interceptions = NULLIF(@mentality_interceptions, ''), 
        mentality_positioning = NULLIF(@mentality_positioning,''), 
        mentality_vision = NULLIF(@mentality_vision, ''), 
		mentality_penalties = NULLIF(@mentality_penalties, ''), 
        mentality_composure = NULLIF(@mentality_composure, ''), 
        defending_marking_awareness = NULLIF(@defending_marking_awareness, ''), 
        defending_standing_tackle = NULLIF(@defending_standing_tackle, ''), 
        defending_sliding_tackle = NULLIF(@defending_sliding_tackle, ''), 
        goalkeeping_diving = NULLIF(@goalkeeping_diving, ''), 
		goalkeeping_handling = NULLIF(@goalkeeping_handling, ''), 
        goalkeeping_kicking = NULLIF(@goalkeeping_kicking, ''), 
        goalkeeping_positioning = NULLIF(@goalkeeping_positioning, ''), 
        goalkeeping_reflexes = NULLIF(@goalkeeping_reflexes, ''), 
        goalkeeping_speed = NULLIF(@goalkeeping_speed, '');




-- Loading data from CSV file into mega table
LOAD DATA INFILE 'c:\\wamp64\\tmp\\fifaProj\\players_16.csv' INTO TABLE fifaData 
	FIELDS ENCLOSED BY '"' TERMINATED BY ','
	LINES TERMINATED BY '\n'
    IGNORE 1 ROWS
    
    (gender, fifaYear, sofifa_id, player_url, short_name, long_name, player_positions, overall, potential,@value_eur, @wage_eur, age, dob, height_cm, 
    weight_kg, @club_team_id, club_name, league_name, league_level, club_position, @club_jersey_number, club_loaned_from, club_joined, 
    @club_contract_valid_until, nationality_id, nationality_name, @nation_team_id, nation_position, @nation_jersey_number, preferred_foot,
    weak_foot, skill_moves, international_reputation, work_rate, body_type, real_face, @release_clause_eur, player_tags, player_traits,
    @pace, @shooting, @passing, @dribbling, @defending, @physic, @attacking_crossing, @attacking_finishing, @attacking_heading_accuracy, 
    @attacking_short_passing, @attacking_volleys, @skill_dribbling, @skill_curve, @skill_fk_accuracy, @skill_long_passing, @skill_ball_control, 
    @movement_acceleration, @movement_sprint_speed, @movement_agility, @movement_reactions, @movement_balance, @power_shot_power, @power_jumping, 
    @power_stamina, @power_strength, @power_long_shots, @mentality_aggression, @mentality_interceptions, @mentality_positioning, @mentality_vision, 
    @mentality_penalties, @mentality_composure, @defending_marking_awareness, @defending_standing_tackle, @defending_sliding_tackle, @goalkeeping_diving, 
    @goalkeeping_handling, @goalkeeping_kicking, @goalkeeping_positioning, @goalkeeping_reflexes, @goalkeeping_speed, ls, st, rs, lw, lf, cf, rf, rw, lam, cam, ram, 
    lm, lcm, cm, rcm, rm, lwb, ldm, cdm, rdm, rwb, lb, lcb, cb, rcb, rb, gk, player_face_url,club_logo_url,club_flag_url,
    nation_logo_url, nation_flag_url)
    SET
		value_eur = NULLIF(@value_eur, ''),
        wage_eur = NULLIF(@wage_eur, ''),
        club_team_id = NULLIF(@club_team_id, ''),
        club_jersey_number = NULLIF(@club_jersey_number, ''),
        club_contract_valid_until = NULLIF(@club_contract_valid_until, ''),
		nation_team_id = NULLIF(@nation_team_id, ''),
        nation_jersey_number = NULLIF(@nation_jersey_number, ''),
        release_clause_eur = NULLIF(@release_clause_eur, ''),
        pace = NULLIF(@pace, ''), 
        shooting = NULLIF(@shooting, ''), 
        passing = NULLIF(@passing, ''), 
        dribbling = NULLIF(@dribbling, ''), 
        defending = NULLIF(@defending, ''), 
        physic = NULLIF(@physic, ''), 
        attacking_crossing = NULLIF(@attacking_crossing, ''), 
        attacking_finishing = NULLIF(@attacking_finishing, ''), 
        attacking_heading_accuracy = NULLIF(@attacking_heading_accuracy, ''), 
		attacking_short_passing = NULLIF(@attacking_short_passing, ''), 
        attacking_volleys = NULLIF(@attacking_volleys, ''), 
        skill_dribbling = NULLIF(@skill_dribbling, ''), 
        skill_curve = NULLIF(@skill_curve, ''), 
        skill_fk_accuracy = NULLIF(@skill_fk_accuracy, ''), 
        skill_long_passing = NULLIF(@skill_long_passing, ''), 
        skill_ball_control = NULLIF(@skill_ball_control, ''), 
		movement_acceleration = NULLIF(@movement_acceleration, ''), 
        movement_sprint_speed = NULLIF(@movement_sprint_speed, ''), 
        movement_agility = NULLIF(@movement_agility, ''), 
        movement_reactions = NULLIF(@movement_reactions, ''), 
        movement_balance = NULLIF(@movement_balance, ''), 
        power_shot_power = NULLIF(@power_shot_power, ''), 
        power_jumping = NULLIF(@power_jumping, ''), 
		power_stamina = NULLIF(@power_stamina, ''), 
        power_strength = NULLIF(@power_strength, ''), 
        power_long_shots = NULLIF(@power_long_shots, ''), 
        mentality_aggression = NULLIF(@mentality_aggression, ''), 
        mentality_interceptions = NULLIF(@mentality_interceptions, ''), 
        mentality_positioning = NULLIF(@mentality_positioning,''), 
        mentality_vision = NULLIF(@mentality_vision, ''), 
		mentality_penalties = NULLIF(@mentality_penalties, ''), 
        mentality_composure = NULLIF(@mentality_composure, ''), 
        defending_marking_awareness = NULLIF(@defending_marking_awareness, ''), 
        defending_standing_tackle = NULLIF(@defending_standing_tackle, ''), 
        defending_sliding_tackle = NULLIF(@defending_sliding_tackle, ''), 
        goalkeeping_diving = NULLIF(@goalkeeping_diving, ''), 
		goalkeeping_handling = NULLIF(@goalkeeping_handling, ''), 
        goalkeeping_kicking = NULLIF(@goalkeeping_kicking, ''), 
        goalkeeping_positioning = NULLIF(@goalkeeping_positioning, ''), 
        goalkeeping_reflexes = NULLIF(@goalkeeping_reflexes, ''), 
        goalkeeping_speed = NULLIF(@goalkeeping_speed, '');




-- Loading data from CSV file into mega table
LOAD DATA INFILE 'c:\\wamp64\\tmp\\fifaProj\\female_players_16.csv' INTO TABLE fifaData 
	FIELDS ENCLOSED BY '"' TERMINATED BY ','
	LINES TERMINATED BY '\n'
    IGNORE 1 ROWS
    
    (gender, fifaYear, sofifa_id, player_url, short_name, long_name, player_positions, overall, potential,@value_eur, @wage_eur, age, dob, height_cm, 
    weight_kg, @club_team_id, club_name, league_name, league_level, club_position, @club_jersey_number, club_loaned_from, club_joined, 
    @club_contract_valid_until, nationality_id, nationality_name, @nation_team_id, nation_position, @nation_jersey_number, preferred_foot,
    weak_foot, skill_moves, international_reputation, work_rate, body_type, real_face, @release_clause_eur, player_tags, player_traits,
    @pace, @shooting, @passing, @dribbling, @defending, @physic, @attacking_crossing, @attacking_finishing, @attacking_heading_accuracy, 
    @attacking_short_passing, @attacking_volleys, @skill_dribbling, @skill_curve, @skill_fk_accuracy, @skill_long_passing, @skill_ball_control, 
    @movement_acceleration, @movement_sprint_speed, @movement_agility, @movement_reactions, @movement_balance, @power_shot_power, @power_jumping, 
    @power_stamina, @power_strength, @power_long_shots, @mentality_aggression, @mentality_interceptions, @mentality_positioning, @mentality_vision, 
    @mentality_penalties, @mentality_composure, @defending_marking_awareness, @defending_standing_tackle, @defending_sliding_tackle, @goalkeeping_diving, 
    @goalkeeping_handling, @goalkeeping_kicking, @goalkeeping_positioning, @goalkeeping_reflexes, @goalkeeping_speed, ls, st, rs, lw, lf, cf, rf, rw, lam, cam, ram, 
    lm, lcm, cm, rcm, rm, lwb, ldm, cdm, rdm, rwb, lb, lcb, cb, rcb, rb, gk, player_face_url,club_logo_url,club_flag_url,
    nation_logo_url, nation_flag_url)
    SET
		value_eur = NULLIF(@value_eur, ''),
        wage_eur = NULLIF(@wage_eur, ''),
        club_team_id = NULLIF(@club_team_id, ''),
        club_jersey_number = NULLIF(@club_jersey_number, ''),
        club_contract_valid_until = NULLIF(@club_contract_valid_until, ''),
		nation_team_id = NULLIF(@nation_team_id, ''),
        nation_jersey_number = NULLIF(@nation_jersey_number, ''),
        release_clause_eur = NULLIF(@release_clause_eur, ''),
        pace = NULLIF(@pace, ''), 
        shooting = NULLIF(@shooting, ''), 
        passing = NULLIF(@passing, ''), 
        dribbling = NULLIF(@dribbling, ''), 
        defending = NULLIF(@defending, ''), 
        physic = NULLIF(@physic, ''), 
        attacking_crossing = NULLIF(@attacking_crossing, ''), 
        attacking_finishing = NULLIF(@attacking_finishing, ''), 
        attacking_heading_accuracy = NULLIF(@attacking_heading_accuracy, ''), 
		attacking_short_passing = NULLIF(@attacking_short_passing, ''), 
        attacking_volleys = NULLIF(@attacking_volleys, ''), 
        skill_dribbling = NULLIF(@skill_dribbling, ''), 
        skill_curve = NULLIF(@skill_curve, ''), 
        skill_fk_accuracy = NULLIF(@skill_fk_accuracy, ''), 
        skill_long_passing = NULLIF(@skill_long_passing, ''), 
        skill_ball_control = NULLIF(@skill_ball_control, ''), 
		movement_acceleration = NULLIF(@movement_acceleration, ''), 
        movement_sprint_speed = NULLIF(@movement_sprint_speed, ''), 
        movement_agility = NULLIF(@movement_agility, ''), 
        movement_reactions = NULLIF(@movement_reactions, ''), 
        movement_balance = NULLIF(@movement_balance, ''), 
        power_shot_power = NULLIF(@power_shot_power, ''), 
        power_jumping = NULLIF(@power_jumping, ''), 
		power_stamina = NULLIF(@power_stamina, ''), 
        power_strength = NULLIF(@power_strength, ''), 
        power_long_shots = NULLIF(@power_long_shots, ''), 
        mentality_aggression = NULLIF(@mentality_aggression, ''), 
        mentality_interceptions = NULLIF(@mentality_interceptions, ''), 
        mentality_positioning = NULLIF(@mentality_positioning,''), 
        mentality_vision = NULLIF(@mentality_vision, ''), 
		mentality_penalties = NULLIF(@mentality_penalties, ''), 
        mentality_composure = NULLIF(@mentality_composure, ''), 
        defending_marking_awareness = NULLIF(@defending_marking_awareness, ''), 
        defending_standing_tackle = NULLIF(@defending_standing_tackle, ''), 
        defending_sliding_tackle = NULLIF(@defending_sliding_tackle, ''), 
        goalkeeping_diving = NULLIF(@goalkeeping_diving, ''), 
		goalkeeping_handling = NULLIF(@goalkeeping_handling, ''), 
        goalkeeping_kicking = NULLIF(@goalkeeping_kicking, ''), 
        goalkeeping_positioning = NULLIF(@goalkeeping_positioning, ''), 
        goalkeeping_reflexes = NULLIF(@goalkeeping_reflexes, ''), 
        goalkeeping_speed = NULLIF(@goalkeeping_speed, '');




-- Loading data from CSV file into mega table
LOAD DATA INFILE 'c:\\wamp64\\tmp\\fifaProj\\players_15.csv' INTO TABLE fifaData 
	FIELDS ENCLOSED BY '"' TERMINATED BY ','
	LINES TERMINATED BY '\n'
    IGNORE 1 ROWS
    
    (gender, fifaYear, sofifa_id, player_url, short_name, long_name, player_positions, overall, potential,@value_eur, @wage_eur, age, dob, height_cm, 
    weight_kg, @club_team_id, club_name, league_name, league_level, club_position, @club_jersey_number, club_loaned_from, club_joined, 
    @club_contract_valid_until, nationality_id, nationality_name, @nation_team_id, nation_position, @nation_jersey_number, preferred_foot,
    weak_foot, skill_moves, international_reputation, work_rate, body_type, real_face, @release_clause_eur, player_tags, player_traits,
    @pace, @shooting, @passing, @dribbling, @defending, @physic, @attacking_crossing, @attacking_finishing, @attacking_heading_accuracy, 
    @attacking_short_passing, @attacking_volleys, @skill_dribbling, @skill_curve, @skill_fk_accuracy, @skill_long_passing, @skill_ball_control, 
    @movement_acceleration, @movement_sprint_speed, @movement_agility, @movement_reactions, @movement_balance, @power_shot_power, @power_jumping, 
    @power_stamina, @power_strength, @power_long_shots, @mentality_aggression, @mentality_interceptions, @mentality_positioning, @mentality_vision, 
    @mentality_penalties, @mentality_composure, @defending_marking_awareness, @defending_standing_tackle, @defending_sliding_tackle, @goalkeeping_diving, 
    @goalkeeping_handling, @goalkeeping_kicking, @goalkeeping_positioning, @goalkeeping_reflexes, @goalkeeping_speed, ls, st, rs, lw, lf, cf, rf, rw, lam, cam, ram, 
    lm, lcm, cm, rcm, rm, lwb, ldm, cdm, rdm, rwb, lb, lcb, cb, rcb, rb, gk, player_face_url,club_logo_url,club_flag_url,
    nation_logo_url, nation_flag_url)
    SET
		value_eur = NULLIF(@value_eur, ''),
        wage_eur = NULLIF(@wage_eur, ''),
        club_team_id = NULLIF(@club_team_id, ''),
        club_jersey_number = NULLIF(@club_jersey_number, ''),
        club_contract_valid_until = NULLIF(@club_contract_valid_until, ''),
		nation_team_id = NULLIF(@nation_team_id, ''),
        nation_jersey_number = NULLIF(@nation_jersey_number, ''),
        release_clause_eur = NULLIF(@release_clause_eur, ''),
        pace = NULLIF(@pace, ''), 
        shooting = NULLIF(@shooting, ''), 
        passing = NULLIF(@passing, ''), 
        dribbling = NULLIF(@dribbling, ''), 
        defending = NULLIF(@defending, ''), 
        physic = NULLIF(@physic, ''), 
        attacking_crossing = NULLIF(@attacking_crossing, ''), 
        attacking_finishing = NULLIF(@attacking_finishing, ''), 
        attacking_heading_accuracy = NULLIF(@attacking_heading_accuracy, ''), 
		attacking_short_passing = NULLIF(@attacking_short_passing, ''), 
        attacking_volleys = NULLIF(@attacking_volleys, ''), 
        skill_dribbling = NULLIF(@skill_dribbling, ''), 
        skill_curve = NULLIF(@skill_curve, ''), 
        skill_fk_accuracy = NULLIF(@skill_fk_accuracy, ''), 
        skill_long_passing = NULLIF(@skill_long_passing, ''), 
        skill_ball_control = NULLIF(@skill_ball_control, ''), 
		movement_acceleration = NULLIF(@movement_acceleration, ''), 
        movement_sprint_speed = NULLIF(@movement_sprint_speed, ''), 
        movement_agility = NULLIF(@movement_agility, ''), 
        movement_reactions = NULLIF(@movement_reactions, ''), 
        movement_balance = NULLIF(@movement_balance, ''), 
        power_shot_power = NULLIF(@power_shot_power, ''), 
        power_jumping = NULLIF(@power_jumping, ''), 
		power_stamina = NULLIF(@power_stamina, ''), 
        power_strength = NULLIF(@power_strength, ''), 
        power_long_shots = NULLIF(@power_long_shots, ''), 
        mentality_aggression = NULLIF(@mentality_aggression, ''), 
        mentality_interceptions = NULLIF(@mentality_interceptions, ''), 
        mentality_positioning = NULLIF(@mentality_positioning,''), 
        mentality_vision = NULLIF(@mentality_vision, ''), 
		mentality_penalties = NULLIF(@mentality_penalties, ''), 
        mentality_composure = NULLIF(@mentality_composure, ''), 
        defending_marking_awareness = NULLIF(@defending_marking_awareness, ''), 
        defending_standing_tackle = NULLIF(@defending_standing_tackle, ''), 
        defending_sliding_tackle = NULLIF(@defending_sliding_tackle, ''), 
        goalkeeping_diving = NULLIF(@goalkeeping_diving, ''), 
		goalkeeping_handling = NULLIF(@goalkeeping_handling, ''), 
        goalkeeping_kicking = NULLIF(@goalkeeping_kicking, ''), 
        goalkeeping_positioning = NULLIF(@goalkeeping_positioning, ''), 
        goalkeeping_reflexes = NULLIF(@goalkeeping_reflexes, ''), 
        goalkeeping_speed = NULLIF(@goalkeeping_speed, '');


SELECT *
FROM fifadata
WHERE fifaYear = '2015'
LIMIT 1000;

SELECT nationality_id
FROM fifaData
GROUP BY nationality_id
HAVING COUNT(DISTINCT nationality_name) > 1;


-- Not Valid
-- SELECT sofifa_id
-- FROM fifaData
-- GROUP BY sofifa_id
-- HAVING COUNT(DISTINCT long_name) > 1;

SELECT sofifa_id, fifaYear
FROM fifaData
GROUP BY sofifa_id, fifaYear
HAVING NOT (MIN(long_name) <=> MAX(long_name));


SELECT sofifa_id, fifaYear
FROM fifaData
GROUP BY sofifa_id, fifaYear
HAVING NOT (MIN(short_name) <=> MAX(short_name));

-- Not valid
-- SELECT long_name
-- FROM fifaData
-- GROUP BY long_name
-- HAVING COUNT(DISTINCT short_name) > 1;

SELECT club_team_id
FROM fifaData
GROUP BY club_team_id
HAVING COUNT(DISTINCT club_name) > 1;